## Help your hedge fund manager!

You have two datasets at your disposal: `Balance_Sheet.xlsx` and `Income_Statement.xlsx`. Both these datasets have three columns in common:
- `"Company"`: The company's ticker name.
- `"comp_type"` The type of industry the company in question belongs to. It is either `"tech"` for companies in the technology industry, `"fmcg"` for companies in the fast-moving consumer goods industry, and `"real_est"` for companies in the real estate industry. 
- `"Year"`: The year the company's information is from.

The rest of the columns in the datasets contain information from the financial statement of the `"Company"` in question. Note that the columns in `Balance_Sheet.xlsx` only contain financial information from the balance sheet. Similarly, the columns in `Income_Statement.xlsx` only contain financial information from the income statement. The columns are named accordingly. For instance, the column `"Total Liab"` from `Balance_Sheet.xlsx` is the total liability.

In [24]:
import numpy as np
import pandas as pd
import seaborn as sns

In [25]:
balance_sheet = pd.read_excel("data/Balance_Sheet.xlsx")
income_statement = pd.read_excel("data/Income_Statement.xlsx")

In [26]:
df = pd.merge(balance_sheet, income_statement, on=["company", "comp_type", "Year"])

In [27]:
df.head()

   Unnamed: 0_x  Year  ... Total Operating Expenses Total Revenue
0             0  2019  ...             196244000000  260174000000
1             1  2020  ...             208227000000  274515000000
2             2  2021  ...             256868000000  365817000000
3             3  2022  ...             274891000000  394328000000
4             4  2019  ...              82884000000  125843000000

[5 rows x 20 columns]

In [28]:
# Compute leverage ratio (Debt-to-Equity)
df["leverage_ratio"] = df["Total Liab"] / df["Total Stockholder Equity"]

In [29]:
# Compute profitability ratio (Operating Margin)
df["profitability_ratio"] = df["Operating Income"] / df["Total Revenue"]

In [30]:
# Create df_ratios with relevant columns
df_ratios = df[["company", "comp_type", "Year", "leverage_ratio", "profitability_ratio"]]

In [31]:
# Find the company type with the lowest profitability ratio
lowest_profitability = df_ratios.groupby("comp_type")["profitability_ratio"].mean().idxmin()

In [32]:
# Find the company type with the highest leverage ratio
highest_leverage = df_ratios.groupby("comp_type")["leverage_ratio"].mean().idxmax()

In [33]:
# Analyze the relationship between leverage and profitability in real estate companies
real_estate_data = df_ratios[df_ratios["comp_type"] == "real_est"]
correlation = real_estate_data["leverage_ratio"].corr(real_estate_data["profitability_ratio"])

if correlation > 0:
    relationship = "positive"
elif correlation < 0:
    relationship = "negative"
else:
    relationship = "no relationship"

In [34]:
# Display results
print("Company type with lowest profitability ratio:", lowest_profitability)
print("Company type with highest leverage ratio:", highest_leverage)
print("Relationship between leverage and profitability in real estate:", relationship)

Company type with lowest profitability ratio: fmcg
Company type with highest leverage ratio: real_est
Relationship between leverage and profitability in real estate: positive